linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - bodyclose
    - noctx
    - prealloc

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/aaronmaturen/go-jira
  misspell:
    locale: US
    ignore-words:
      - favourite
      - favourites

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - bodyclose
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  tests: true
